version: '3.9'

x-index-pg-access: &index-pg-access
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  POSTGRES_DB: ${POSTGRES_DB:-ton_index}

services:
  event-cache:
    image: redis:latest
    networks:
      - internal
    command: redis-server --maxclients 40000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.${TONCENTER_ENV:?}.indexer-cpp.events==true"
  event-classifier:
    image: ${DOCKER_REGISTRY:-localhost:5000}/ton-index-event-classfier:${IMAGE_TAG:?}
    build:
      context: .
      dockerfile: Dockerfile
      target: classifier
    secrets:
      - postgres_password
    command: --pool-size ${TON_INDEXER_WORKERS:-8} --prefetch-size 1000 --batch-size 100 --expected-total 720000000
    environment: 
      <<: *index-pg-access
      TON_INDEXER_REDIS_DSN: redis://event-cache:6379
      TON_INDEXER_IS_TESTNET: ${TON_INDEXER_IS_TESTNET:-0}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.${TONCENTER_ENV:?}.indexer-cpp.events==true"
    networks:
      internal:

networks:
  internal:
    attachable: true
    external: false
    driver_opts:
      com.docker.network.driver.mtu: 1350
  toncenter-global:
    external: true

secrets:
  postgres_password:
    file: private/postgres_password
  