indexer:
  liteserver_config: toncenter-game.conf
  workers_count: ${WORKERS_COUNT}
  init_mc_seqno: 19891542
  smallest_mc_seqno: 0
  blocks_per_task: 30
  max_tasks_per_child: 50
  task_time_limit: 60
postgres:
  host: postgres
  port: 5432
  user: postgres
  password_file: /run/secrets/postgres_password
  dbname: ton_index