webserver:
  api_root_path: ${ROOT_PATH}
indexer:
  liteserver_config: ${LITESERVER_CONFIG}
  ls_index: ${LITESERVER_INDEX}
  use_ext_method: ${USE_GET_BLOCK_TRANSACTIONS_EXT}
  cdll_path: ${CDLL_PATH}
  workers_count: ${WORKERS_COUNT}
  init_mc_seqno: ${START_SEQNO}
  smallest_mc_seqno: ${BOTTOM_SEQNO}
  blocks_per_task: 30
  max_tasks_per_child: 50
  task_time_limit: 1200
  accounts_index_batch: 1000
  accounts_index_min_interval_days: ${ACCOUNTS_INDEX_MIN_INTERVAL_DAYS}
  accounts_per_task: 50
  discover_accounts_enabled: ${DISCOVER_ACCOUNTS_ENABLED}
parser:
  max_tasks_per_child: 60
  task_time_limit: 1200
  poll_interval: 30
  batch_size: 10
  executor:
    url: ${PARSER_EXECUTOR_URL}
  retry:
    timeout: 300
postgres:
  host: postgres
  port: 5432
  user: postgres
  password_file: /run/secrets/postgres_password
  dbname: ton_index
eventbus:
  enabled: ${EVENTBUS_ENABLED}
  messages:
    enabled: ${MESSAGES_KAFKA_STREAM}
    topic: messages
  kafka:
    broker: ${EVENTBUS_KAFKA_BROKER}
    topic: ${EVENTBUS_KAFKA_TOPIC}
